package com.example.imagesplitterv2

import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Rect
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.*
import kotlinx.android.synthetic.main.activity_split_image.*

class SplitImageActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_split_image)

        horVer()
        splitVariation()

        backBtn1x2.setOnClickListener() {
            var intentReturn = Intent(this, MainActivity::class.java)
            startActivity(intentReturn)
        }
    }

    private fun horVer () {
        val horizontal = this.intent.getStringExtra("Horizontal")
        if (horizontal.isEmpty()) {
            textViewHorizontal.text = ""
        } else {
            textViewHorizontal.text = (horizontal)
        }

        val vertical = this.intent.getStringExtra("Vertical")
        if (vertical.isEmpty()) {
            textViewVertical.text = ""
        } else {
            textViewVertical.text = (vertical)
        }
    }

    private fun splitVariation() {

        if (textViewHorizontal.text.toString() == 2.toString() && textViewVertical.text.toString() == 2.toString()) {
            splitImage2x2()
        } else if (textViewHorizontal.text.toString() == 3.toString() && textViewVertical.text.toString() == 2.toString()) {
            splitImage3x2()
        } else if (textViewHorizontal.text.toString() == 2.toString() && textViewVertical.text.toString() == 3.toString()) {
            splitImage2x3()
        } else if (textViewHorizontal.text.toString() == 3.toString() && textViewVertical.text.toString() == 3.toString()) {
            splitImage3x3()
        } else if (textViewHorizontal.text.toString() == 3.toString() && textViewVertical.text.toString() == 4.toString()) {
            splitImage3x4()
        } else if (textViewHorizontal.text.toString() == 3.toString() && textViewVertical.text.toString() == 5.toString()) {
            splitImage3x5()
        } else if (textViewHorizontal.text.toString() == 4.toString() && textViewVertical.text.toString() == 2.toString()) {
            splitImage4x2()
        } else if (textViewHorizontal.text.toString() == 2.toString() && textViewVertical.text.toString() == 4.toString()) {
            splitImage2x4()
        } else if (textViewHorizontal.text.toString() == 4.toString() && textViewVertical.text.toString() == 3.toString()) {
            splitImage4x3()
        } else if (textViewHorizontal.text.toString() == 4.toString() && textViewVertical.text.toString() == 4.toString()) {
            splitImage4x4()
        } else if (textViewHorizontal.text.toString() == 4.toString() && textViewVertical.text.toString() == 5.toString()) {
            splitImage4x5()
        } else if (textViewHorizontal.text.toString() == 5.toString() && textViewVertical.text.toString() == 2.toString()) {
            splitImage5x2()
        } else if (textViewHorizontal.text.toString() == 2.toString() && textViewVertical.text.toString() == 5.toString()) {
            splitImage2x5()
        } else if (textViewHorizontal.text.toString() == 5.toString() && textViewVertical.text.toString() == 5.toString()) {
            splitImage5x5()
        } else if (textViewHorizontal.text.toString() == 5.toString() && textViewVertical.text.toString() == 3.toString()) {
            splitImage5x3()
        } else if (textViewHorizontal.text.toString() == 5.toString() && textViewVertical.text.toString() == 4.toString()) {
            splitImage5x4()
        } else {
            Toast.makeText(this, "xyz", Toast.LENGTH_SHORT).show()
        }
    }

    private fun splitImage2x2() {

        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmapTopLeft = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvasTopLeft = Canvas(cutBitmapTopLeft)
        var desRectTopLeft = Rect(0, 0, bitmap.width / 2, bitmap.height / 2)
        var srcRectTopLeft = Rect(0, 0, bitmap.width /2, bitmap.height / 2)
        canvasTopLeft.drawBitmap(bitmap, srcRectTopLeft, desRectTopLeft, null)
        myImageViewSplit1.setImageBitmap(cutBitmapTopLeft)

        var cutBitmapTopRight = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvasTopRight = Canvas(cutBitmapTopRight)
        var desRectTopRight = Rect(0, 0, bitmap.width / 2, bitmap.height / 2)
        var srcRectTopRight = Rect(bitmap.width / 2, 0, bitmap.width, bitmap.height / 2)
        canvasTopRight.drawBitmap(bitmap, srcRectTopRight, desRectTopRight, null)
        myImageViewSplit2.setImageBitmap(cutBitmapTopRight)

        var cutBitmapBottomLeft = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvasBottomLeft = Canvas(cutBitmapBottomLeft)
        var desRectBottomLeft = Rect(0, 0, bitmap.width / 2, bitmap.height / 2)
        var srcRectBottomLeft = Rect(0, bitmap.height / 2, bitmap.width / 2, bitmap.height)
        canvasBottomLeft.drawBitmap(bitmap, srcRectBottomLeft, desRectBottomLeft, null)
        myImageViewSplit3.setImageBitmap(cutBitmapBottomLeft)

        var cutBitmapBottomRight = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvasBottomRight = Canvas(cutBitmapBottomRight)
        var desRectBottomRight = Rect(0, 0, bitmap.width / 2, bitmap.height / 2)
        var srcRectBottomRight = Rect(bitmap.width / 2, bitmap.height / 2, bitmap.width, bitmap.height)
        canvasBottomRight.drawBitmap(bitmap, srcRectBottomRight, desRectBottomRight, null)
        myImageViewSplit4.setImageBitmap(cutBitmapBottomRight)
    }

    private fun splitImage3x2() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 3, bitmap.height / 2)
        var srcRect1 = Rect(0, 0, bitmap.width /3, bitmap.height / 2)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit5.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 3, bitmap.height / 2)
        var srcRect2 = Rect(bitmap.width / 3, 0, 2 * bitmap.width / 3, bitmap.height / 2)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit6.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 3, bitmap.height / 2)
        var srcRect3 = Rect(2 * bitmap.width / 3, 0, bitmap.width, bitmap.height / 2)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit7.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 3, bitmap.height / 2)
        var srcRect4 = Rect(0, bitmap.height / 2, bitmap.width /3, bitmap.height)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit8.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 3, bitmap.height / 2)
        var srcRect5 = Rect(bitmap.width / 3, bitmap.height / 2, 2 * bitmap.width / 3, bitmap.height)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit9.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 3, bitmap.height / 2)
        var srcRect6 = Rect(2 * bitmap.width / 3, bitmap.height / 2, bitmap.width, bitmap.height)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit10.setImageBitmap(cutBitmap6)
    }

    private fun splitImage2x3() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        var srcRect1 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit11.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        var srcRect2 = Rect(0, bitmap.height / 3, bitmap.width / 2, 2 * bitmap.height / 3)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit13.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        var srcRect3 = Rect(0, 2 * bitmap.height / 3,bitmap.width / 2, bitmap.height)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit15.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        var srcRect4 = Rect( bitmap.height / 2,0, bitmap.width, bitmap.height / 3)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit12.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        var srcRect5 = Rect(bitmap.width / 2, bitmap.height / 3, bitmap.width,2 * bitmap.height / 3)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit14.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 2, bitmap.height / 3)
        var srcRect6 = Rect(bitmap.width / 2, 2 * bitmap.height / 3, bitmap.width, bitmap.height)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit16.setImageBitmap(cutBitmap6)
    }

    private fun splitImage4x2() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit17.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect2 = Rect(bitmap.width / 4, 0, bitmap.width / 2, bitmap.height / 2)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit18.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect3 = Rect(bitmap.width / 2, 0, 3 * bitmap.width / 4, bitmap.height / 2)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit19.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect4 = Rect(3 * bitmap.width / 4, 0, bitmap.width, bitmap.height / 2)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit20.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect5 = Rect(0, bitmap.height / 2, bitmap.width / 4, bitmap.height)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit21.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect6 = Rect(bitmap.width / 4, bitmap.height / 2, bitmap.width / 2, bitmap.height)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit22.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect7 = Rect(bitmap.width / 2, bitmap.height / 2, 3 * bitmap.width / 4, bitmap.height)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit23.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 4, bitmap.height / 2)
        var srcRect8 = Rect(3 * bitmap.width / 4, bitmap.height / 2, bitmap.width, bitmap.height)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit24.setImageBitmap(cutBitmap8)
    }

    private fun splitImage2x4() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect1 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit25.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect2 = Rect(0, bitmap.height / 4, bitmap.width / 2, bitmap.height / 2)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit27.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect3 = Rect(0, bitmap.height / 2, bitmap.width / 2, 3 * bitmap.height / 4)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit29.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect4 = Rect(0, 3 * bitmap.height / 4, bitmap.width / 2, bitmap.height)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit31.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect5 = Rect(bitmap.width / 2, 0, bitmap.width, bitmap.height / 4)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit26.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect6 = Rect(bitmap.width / 2, bitmap.height / 4, bitmap.width, bitmap.height / 2)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit28.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect7 = Rect(bitmap.width / 2, bitmap.height / 2, bitmap.width, 3 * bitmap.height / 4)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit30.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 2, bitmap.height / 4)
        var srcRect8 = Rect(bitmap.width / 2, 3 * bitmap.height / 4, bitmap.width, bitmap.height)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit32.setImageBitmap(cutBitmap8)
    }

    private fun splitImage5x2() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit33.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect2 = Rect(bitmap.width / 5, 0, 2 * bitmap.width / 5, bitmap.height / 2)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit34.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect3 = Rect(2 * bitmap.width / 5, 0, 3 * bitmap.width / 5, bitmap.height / 2)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit35.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect4 = Rect(3 * bitmap.width / 5, 0, 4 * bitmap.width / 5, bitmap.height / 2)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit36.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect5 = Rect(4 * bitmap.width / 5, 0, bitmap.width, bitmap.height / 2)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit37.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect6 = Rect(0, bitmap.height / 2, bitmap.width / 5, bitmap.height)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit38.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect7 = Rect(bitmap.width / 5, bitmap.height / 2, 2 * bitmap.width / 5, bitmap.height)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit39.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect8 = Rect(2 * bitmap.width / 5, bitmap.height / 2, 3 * bitmap.width / 5, bitmap.height)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit40.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect9 = Rect(3 * bitmap.width / 5, bitmap.height / 2, 4 * bitmap.width / 5, bitmap.height)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit41.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 2, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect10 = Rect(4 * bitmap.width / 5, bitmap.height / 2, bitmap.width, bitmap.height)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit42.setImageBitmap(cutBitmap10)
    }

    private fun splitImage2x5() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect1 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit43.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect2 = Rect(0, bitmap.height / 5, bitmap.width / 2, 2 * bitmap.height / 5)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit45.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect3 = Rect(0, 2 * bitmap.height / 5, bitmap.width / 2, 3 * bitmap.height / 5)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit47.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect4 = Rect(0, 3 * bitmap.height / 5, bitmap.width / 2, 4 * bitmap.height / 5)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit49.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect5 = Rect(0, 4 * bitmap.height / 5, bitmap.width / 2, bitmap.height)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit51.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect6 = Rect(bitmap.width / 2, 0, bitmap.width, bitmap.height / 5)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit44.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect7 = Rect(bitmap.width / 2, bitmap.height / 5, bitmap.width, 2 * bitmap.height / 5)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit46.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect8 = Rect(bitmap.width / 2, 2 * bitmap.height / 5, bitmap.width, 3 * bitmap.height / 5)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit48.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect9 = Rect(bitmap.width / 2, 3 * bitmap.height / 5, bitmap.width, 4 * bitmap.height / 5)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit50.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 2, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 2, bitmap.height / 5)
        var srcRect10 = Rect(bitmap.width / 2, 4 * bitmap.height / 5, bitmap.width, bitmap.height)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit52.setImageBitmap(cutBitmap10)
    }

    private fun splitImage3x3() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect1 = Rect(0, 0, bitmap.width /3, bitmap.height / 3)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit53.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect2 = Rect(bitmap.width / 3, 0, 2 * bitmap.width / 3, bitmap.height / 3)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit54.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect3 = Rect(2 * bitmap.width / 3, 0, bitmap.width, bitmap.height / 3)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit55.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect4 = Rect(0, bitmap.height / 3, bitmap.width /3, 2 * bitmap.height / 3)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit56.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect5 = Rect(bitmap.width / 3, bitmap.height / 3, 2 * bitmap.width / 3, 2 * bitmap.height / 3)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit57.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect6 = Rect(2 * bitmap.width / 3, bitmap.height / 3, bitmap.width, 2 * bitmap.height / 3)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit58.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect7 = Rect(0, 2 * bitmap.height / 3, bitmap.width /3, bitmap.height)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit59.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect8 = Rect(bitmap.width / 3, 2 * bitmap.height / 3, 2 * bitmap.width / 3, bitmap.height)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit60.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 3, bitmap.height / 3)
        var srcRect9 = Rect(2 * bitmap.width / 3, 2 * bitmap.height / 3, bitmap.width, bitmap.height)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit61.setImageBitmap(cutBitmap9)
    }

    private fun splitImage4x4() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit62.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect2 = Rect(bitmap.width / 4, 0, bitmap.width / 2, bitmap.height / 4)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit63.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect3 = Rect(bitmap.width / 2, 0, 3 * bitmap.width / 4, bitmap.height / 4)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit64.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect4 = Rect(3 * bitmap.width / 4, 0, bitmap.width, bitmap.height / 4)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit65.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect5 = Rect(0, bitmap.height / 4, bitmap.width / 4, bitmap.height / 2)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit66.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect6 = Rect(bitmap.width / 4, bitmap.height / 4, bitmap.width / 2, bitmap.height / 2)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit67.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect7 = Rect(bitmap.width / 2, bitmap.height / 4, 3 * bitmap.width / 4, bitmap.height / 2)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit68.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect8 = Rect(3 * bitmap.width / 4, bitmap.height / 4, bitmap.width, bitmap.height / 2)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit69.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect9 = Rect(0, bitmap.height / 2, bitmap.width / 4, 3 * bitmap.height / 4)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit70.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect10 = Rect(bitmap.width / 4, bitmap.height / 2, bitmap.width / 2, 3 * bitmap.height / 4)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit71.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect11 = Rect(bitmap.width / 2, bitmap.height / 2, 3 * bitmap.width / 4, 3 * bitmap.height / 4)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit72.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect12 = Rect(3 * bitmap.width / 4, bitmap.height / 2, bitmap.width, 3 * bitmap.height / 4)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit73.setImageBitmap(cutBitmap12)

        var cutBitmap13 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas13 = Canvas(cutBitmap13)
        var desRect13 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect13 = Rect(0, 3 * bitmap.height / 4, bitmap.width / 4, bitmap.height)
        canvas13.drawBitmap(bitmap, srcRect13, desRect13, null)
        myImageViewSplit74.setImageBitmap(cutBitmap13)

        var cutBitmap14 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas14 = Canvas(cutBitmap14)
        var desRect14 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect14 = Rect(bitmap.width / 4, 3 * bitmap.height / 4, bitmap.width / 2, bitmap.height)
        canvas14.drawBitmap(bitmap, srcRect14, desRect14, null)
        myImageViewSplit75.setImageBitmap(cutBitmap14)

        var cutBitmap15 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas15 = Canvas(cutBitmap15)
        var desRect15 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect15 = Rect(bitmap.width / 2, 3 * bitmap.height / 4, 3 * bitmap.width / 4, bitmap.height)
        canvas15.drawBitmap(bitmap, srcRect15, desRect15, null)
        myImageViewSplit76.setImageBitmap(cutBitmap15)

        var cutBitmap16 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas16 = Canvas(cutBitmap16)
        var desRect16 = Rect(0, 0, bitmap.width / 4, bitmap.height / 4)
        var srcRect16 = Rect(3 * bitmap.width / 4, 3 * bitmap.height / 4, bitmap.width, bitmap.height)
        canvas16.drawBitmap(bitmap, srcRect16, desRect16, null)
        myImageViewSplit77.setImageBitmap(cutBitmap16)
    }

    private fun splitImage5x5() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit78.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect2 = Rect(bitmap.width / 5, 0, 2 * bitmap.width / 5, bitmap.height / 5)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit79.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect3 = Rect(2 * bitmap.width / 5, 0, 3 * bitmap.width / 5, bitmap.height / 5)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit80.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect4 = Rect(3 * bitmap.width / 5, 0, 4 * bitmap.width / 5, bitmap.height / 5)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit81.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect5 = Rect(4 * bitmap.width / 5, 0, bitmap.width, bitmap.height / 5)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit82.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect6 = Rect(0, bitmap.height / 5, bitmap.width / 5, 2 * bitmap.height / 5)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit83.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 5, bitmap.height / 2)
        var srcRect7 = Rect(bitmap.width / 5, bitmap.height / 5, 2 * bitmap.width / 5,  2 * bitmap.height / 5)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit84.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect8 = Rect(2 * bitmap.width / 5, bitmap.height / 5, 3 * bitmap.width / 5, 2 * bitmap.height / 5)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit85.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect9 = Rect(3 * bitmap.width / 5, bitmap.height / 5, 4 * bitmap.width / 5, 2 * bitmap.height / 5)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit86.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect10 = Rect(4 * bitmap.width / 5, bitmap.height / 5, bitmap.width, 2 * bitmap.height / 5)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit87.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect11 = Rect(0, 2 * bitmap.height / 5, bitmap.width / 5, 3 * bitmap.height / 5)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit88.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect12 = Rect(bitmap.width / 5, 2 * bitmap.height / 5, 2 * bitmap.width / 5, 3 * bitmap.height / 5)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit89.setImageBitmap(cutBitmap12)

        var cutBitmap13 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas13 = Canvas(cutBitmap13)
        var desRect13 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect13 = Rect(2 * bitmap.width / 5, 2 * bitmap.height / 5, 3 * bitmap.width / 5, 3 * bitmap.height / 5)
        canvas13.drawBitmap(bitmap, srcRect13, desRect13, null)
        myImageViewSplit90.setImageBitmap(cutBitmap13)

        var cutBitmap14 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas14 = Canvas(cutBitmap14)
        var desRect14 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect14 = Rect(3 * bitmap.width / 5, 2 * bitmap.height / 5, 4 * bitmap.width / 5, 3 * bitmap.height / 5)
        canvas14.drawBitmap(bitmap, srcRect14, desRect14, null)
        myImageViewSplit91.setImageBitmap(cutBitmap14)

        var cutBitmap15 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas15 = Canvas(cutBitmap15)
        var desRect15 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect15 = Rect(4 * bitmap.width / 5, 2 * bitmap.height / 5, bitmap.width, 3 * bitmap.height / 5)
        canvas15.drawBitmap(bitmap, srcRect15, desRect15, null)
        myImageViewSplit92.setImageBitmap(cutBitmap15)

        var cutBitmap16 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas16 = Canvas(cutBitmap16)
        var desRect16 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect16 = Rect(0, 3 * bitmap.height / 5, bitmap.width / 5, 4 * bitmap.height / 5)
        canvas16.drawBitmap(bitmap, srcRect16, desRect16, null)
        myImageViewSplit93.setImageBitmap(cutBitmap16)

        var cutBitmap17 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas17 = Canvas(cutBitmap17)
        var desRect17 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect17 = Rect(bitmap.width / 5, 3 * bitmap.height / 5, 2 * bitmap.width / 5, 4 * bitmap.height / 5)
        canvas17.drawBitmap(bitmap, srcRect17, desRect17, null)
        myImageViewSplit94.setImageBitmap(cutBitmap17)

        var cutBitmap18 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas18 = Canvas(cutBitmap18)
        var desRect18 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect18 = Rect(2 * bitmap.width / 5, 3 * bitmap.height / 5, 3 * bitmap.width / 5, 4 * bitmap.height / 5)
        canvas18.drawBitmap(bitmap, srcRect18, desRect18, null)
        myImageViewSplit95.setImageBitmap(cutBitmap18)

        var cutBitmap19 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas19 = Canvas(cutBitmap19)
        var desRect19 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect19 = Rect(3 * bitmap.width / 5, 3 * bitmap.height / 5, 4 * bitmap.width / 5, 4 * bitmap.height / 5)
        canvas19.drawBitmap(bitmap, srcRect19, desRect19, null)
        myImageViewSplit96.setImageBitmap(cutBitmap19)

        var cutBitmap20 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas20 = Canvas(cutBitmap20)
        var desRect20 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect20 = Rect(4 * bitmap.width / 5, 3 * bitmap.height / 5, bitmap.width, 4 * bitmap.height / 5)
        canvas20.drawBitmap(bitmap, srcRect20, desRect20, null)
        myImageViewSplit97.setImageBitmap(cutBitmap20)

        var cutBitmap21 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas21 = Canvas(cutBitmap21)
        var desRect21 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect21 = Rect(0, 4 * bitmap.height / 5, bitmap.width / 5, bitmap.height)
        canvas21.drawBitmap(bitmap, srcRect21, desRect21, null)
        myImageViewSplit98.setImageBitmap(cutBitmap21)

        var cutBitmap22 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas22 = Canvas(cutBitmap22)
        var desRect22 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect22 = Rect(bitmap.width / 5, 4 * bitmap.height / 5, 2 * bitmap.width / 5, bitmap.height)
        canvas22.drawBitmap(bitmap, srcRect22, desRect22, null)
        myImageViewSplit99.setImageBitmap(cutBitmap22)

        var cutBitmap23 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas23 = Canvas(cutBitmap23)
        var desRect23 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect23 = Rect(bitmap.width / 2, 4 * bitmap.height / 5, 3 * bitmap.width / 5, bitmap.height)
        canvas23.drawBitmap(bitmap, srcRect23, desRect23, null)
        myImageViewSplit100.setImageBitmap(cutBitmap23)

        var cutBitmap24 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas24 = Canvas(cutBitmap24)
        var desRect24 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect24 = Rect(3 * bitmap.width / 5, 4 * bitmap.height / 5, 4 * bitmap.width / 5, bitmap.height)
        canvas24.drawBitmap(bitmap, srcRect24, desRect24, null)
        myImageViewSplit101.setImageBitmap(cutBitmap24)

        var cutBitmap25 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas25 = Canvas(cutBitmap25)
        var desRect25 = Rect(0, 0, bitmap.width / 5, bitmap.height / 5)
        var srcRect25 = Rect(4 * bitmap.width / 5, 4 * bitmap.height / 5, bitmap.width, bitmap.height)
        canvas25.drawBitmap(bitmap, srcRect25, desRect25, null)
        myImageViewSplit102.setImageBitmap(cutBitmap25)
    }

    private fun splitImage3x4() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect1 = Rect(0, 0, bitmap.width /3, bitmap.height / 4)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit103.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect2 = Rect(bitmap.width / 3, 0, 2 * bitmap.width / 3, bitmap.height / 4)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit104.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect3 = Rect(2 * bitmap.width / 3, 0, bitmap.width, bitmap.height / 4)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit105.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect4 = Rect(0, bitmap.height / 4, bitmap.width /3, bitmap.height / 2)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit106.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect5 = Rect(bitmap.width / 3, bitmap.height / 4, 2 * bitmap.width / 3, bitmap.height / 2)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit107.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect6 = Rect(2 * bitmap.width / 3, bitmap.height / 4, bitmap.width, bitmap.height / 2)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit108.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect7 = Rect(0, bitmap.height / 2, bitmap.width /3, 3 * bitmap.height / 4)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit109.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect8 = Rect(bitmap.width / 3, bitmap.height / 2, 2 * bitmap.width / 3, 3 * bitmap.height / 4)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit110.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect9 = Rect(2 * bitmap.width / 3, bitmap.height / 2, bitmap.width, 3 * bitmap.height / 4)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit111.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect10 = Rect(0, 3 * bitmap.height / 4, bitmap.width /3, bitmap.height)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit112.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect11 = Rect(bitmap.width / 3, 3 * bitmap.height / 4, 2 * bitmap.width / 3, bitmap.height)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit113.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 3, bitmap.height / 4)
        var srcRect12 = Rect(2 * bitmap.width / 3, 3 * bitmap.height / 4, bitmap.width, bitmap.height)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit114.setImageBitmap(cutBitmap12)
    }

    private fun splitImage4x3() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit115.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect2 = Rect(bitmap.width / 4, 0, bitmap.width / 2, bitmap.height / 3)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit116.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect3 = Rect(bitmap.width / 2, 0, 3 * bitmap.width / 4, bitmap.height / 3)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit117.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect4 = Rect(3 * bitmap.width / 4, 0, bitmap.width, bitmap.height / 3)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit118.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect5 = Rect(0, bitmap.height / 3, bitmap.width / 4, 2 * bitmap.height / 3)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit119.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect6 = Rect(bitmap.width / 4, bitmap.height / 3, bitmap.width / 2, 2 * bitmap.height / 3)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit120.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect7 = Rect(bitmap.width / 2, bitmap.height / 3, 3 * bitmap.width / 4, 2 * bitmap.height / 3)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit121.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect8 = Rect(3 * bitmap.width / 4, bitmap.height / 3, bitmap.width, 2 * bitmap.height / 3)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit122.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect9 = Rect(0, 2 * bitmap.height / 3, bitmap.width / 4, bitmap.height)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit123.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect10 = Rect(bitmap.width / 4, 2 * bitmap.height / 3, bitmap.width / 2, bitmap.height)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit124.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect11 = Rect(bitmap.width / 2, 2 * bitmap.height / 3, 3 * bitmap.width / 4, bitmap.height)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit125.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 4, bitmap.height / 3)
        var srcRect12 = Rect(3 * bitmap.width / 4, 2 * bitmap.height / 3, bitmap.width, bitmap.height)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit126.setImageBitmap(cutBitmap12)
    }

    private fun splitImage3x5() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect1 = Rect(0, 0, bitmap.width /3, bitmap.height / 5)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit127.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect2 = Rect(bitmap.width / 3, 0, 2 * bitmap.width / 3, bitmap.height / 5)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit128.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect3 = Rect(2 * bitmap.width / 3, 0, bitmap.width, bitmap.height / 5)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit129.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect4 = Rect(0, bitmap.height / 5, bitmap.width /3, 2 * bitmap.height / 5)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit130.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect5 = Rect(bitmap.width / 3, bitmap.height / 5, 2 * bitmap.width / 3, 2 * bitmap.height / 5)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit131.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect6 = Rect(2 * bitmap.width / 3, bitmap.height / 5, bitmap.width, 2 * bitmap.height / 5)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit132.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect7 = Rect(0, 2 * bitmap.height / 5, bitmap.width /3, 3 * bitmap.height / 5)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit133.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect8 = Rect(bitmap.width / 3, 2 * bitmap.height / 5, 2 * bitmap.width / 3, 3 * bitmap.height / 5)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit134.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect9 = Rect(2 * bitmap.width / 3, 2 * bitmap.height / 5, bitmap.width, 3 * bitmap.height / 5)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit135.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect10 = Rect(0, 3 * bitmap.height / 5, bitmap.width /3, 4 * bitmap.height / 5)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit136.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect11 = Rect(bitmap.width / 3, 3 * bitmap.height / 5, 2 * bitmap.width / 3, 4 * bitmap.height / 5)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit137.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect12 = Rect(2 * bitmap.width / 3, 3 * bitmap.height / 5, bitmap.width, 4 * bitmap.height / 5)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit138.setImageBitmap(cutBitmap12)

        var cutBitmap13 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas13 = Canvas(cutBitmap13)
        var desRect13 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect13 = Rect(0, 4 * bitmap.height / 5, bitmap.width /3, bitmap.height)
        canvas13.drawBitmap(bitmap, srcRect13, desRect13, null)
        myImageViewSplit139.setImageBitmap(cutBitmap13)

        var cutBitmap14 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas14 = Canvas(cutBitmap14)
        var desRect14 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect14 = Rect(bitmap.width / 3, 4 * bitmap.height / 5, 2 * bitmap.width / 3, bitmap.height)
        canvas14.drawBitmap(bitmap, srcRect14, desRect14, null)
        myImageViewSplit140.setImageBitmap(cutBitmap14)

        var cutBitmap15 = Bitmap.createBitmap(bitmap.width / 3, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas15 = Canvas(cutBitmap15)
        var desRect15 = Rect(0, 0, bitmap.width / 3, bitmap.height / 5)
        var srcRect15 = Rect(2 * bitmap.width / 3, 4 * bitmap.height / 5, bitmap.width, bitmap.height)
        canvas15.drawBitmap(bitmap, srcRect15, desRect15, null)
        myImageViewSplit141.setImageBitmap(cutBitmap15)
    }

    private fun splitImage5x3() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit142.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect2 = Rect(bitmap.width / 5, 0, 2 * bitmap.width / 5, bitmap.height / 3)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit143.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect3 = Rect(2 * bitmap.width / 5, 0, 3 * bitmap.width / 5, bitmap.height / 3)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit144.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect4 = Rect(3 * bitmap.width / 5, 0, 4 * bitmap.width / 5, bitmap.height / 3)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit145.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect5 = Rect(4 * bitmap.width / 5, 0, bitmap.width, bitmap.height / 3)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit146.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect6 = Rect(0, bitmap.height / 3, bitmap.width / 5, 2 * bitmap.height / 3)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit147.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect7 = Rect(bitmap.width / 5, bitmap.height / 3, 2 * bitmap.width / 5, 2 * bitmap.height / 3)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit148.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect8 = Rect(2 * bitmap.width / 5, bitmap.height / 3, 3 * bitmap.width / 5, 2 * bitmap.height / 3)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit149.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect9 = Rect(3 * bitmap.width / 5, bitmap.height / 3, 4 * bitmap.width / 5, 2 * bitmap.height / 3)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit150.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect10 = Rect(4 * bitmap.width / 5, bitmap.height / 3, bitmap.width, 2 * bitmap.height / 3)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit151.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect11 = Rect(0, 2 * bitmap.height / 3, bitmap.width / 5, bitmap.height)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit152.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect12 = Rect(bitmap.width / 5, 2 * bitmap.height / 3, 2 * bitmap.width / 5, bitmap.height)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit153.setImageBitmap(cutBitmap12)

        var cutBitmap13 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas13 = Canvas(cutBitmap13)
        var desRect13 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect13 = Rect(2 * bitmap.width / 5, 2 * bitmap.height / 3, 3 * bitmap.width / 5, bitmap.height)
        canvas13.drawBitmap(bitmap, srcRect13, desRect13, null)
        myImageViewSplit154.setImageBitmap(cutBitmap13)

        var cutBitmap14 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas14 = Canvas(cutBitmap14)
        var desRect14 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect14 = Rect(3 * bitmap.width / 5, 2 * bitmap.height / 3, 4 * bitmap.width / 5, bitmap.height)
        canvas14.drawBitmap(bitmap, srcRect14, desRect14, null)
        myImageViewSplit155.setImageBitmap(cutBitmap14)

        var cutBitmap15 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 3, Bitmap.Config.ARGB_8888)
        var canvas15 = Canvas(cutBitmap15)
        var desRect15 = Rect(0, 0, bitmap.width / 5, bitmap.height / 3)
        var srcRect15 = Rect(4 * bitmap.width / 5, 2 * bitmap.height / 3, bitmap.width, bitmap.height)
        canvas15.drawBitmap(bitmap, srcRect15, desRect15, null)
        myImageViewSplit156.setImageBitmap(cutBitmap15)
    }

    private fun splitImage4x5() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect1 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit157.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect2 = Rect(bitmap.width / 4, 0, bitmap.width / 2, bitmap.height / 5)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit158.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect3 = Rect(bitmap.width / 2, 0, 3 * bitmap.width / 4, bitmap.height / 5)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit159.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect4 = Rect(3 * bitmap.width / 4, 0, bitmap.width, bitmap.height / 5)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit160.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect5 = Rect(0, bitmap.height / 5, bitmap.width / 4, 2 * bitmap.height / 5)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit161.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect6 = Rect(bitmap.width / 4, bitmap.height / 5, bitmap.width / 2, 2 * bitmap.height / 5)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit162.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect7 = Rect(bitmap.width / 2, bitmap.height / 5, 3 * bitmap.width / 4, 2 * bitmap.height / 5)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit163.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect8 = Rect(3 * bitmap.width / 4, bitmap.height / 5, bitmap.width, 2 * bitmap.height / 5)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit164.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect9 = Rect(0, 2 * bitmap.height / 5, bitmap.width / 4, 3 * bitmap.height / 5)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit165.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect10 = Rect(bitmap.width / 4, 2 * bitmap.height / 5, bitmap.width / 2, 3 * bitmap.height / 5)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit166.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect11 = Rect(bitmap.width / 2, 2 * bitmap.height / 5, 3 * bitmap.width / 4, 3 * bitmap.height / 5)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit167.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect12 = Rect(3 * bitmap.width / 4, 2 * bitmap.height / 5, bitmap.width, 3 * bitmap.height / 5)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit168.setImageBitmap(cutBitmap12)

        var cutBitmap13 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas13 = Canvas(cutBitmap13)
        var desRect13 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect13 = Rect(0, 3 * bitmap.height / 5, bitmap.width / 4, 4 * bitmap.height / 5)
        canvas13.drawBitmap(bitmap, srcRect13, desRect13, null)
        myImageViewSplit169.setImageBitmap(cutBitmap13)

        var cutBitmap14 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas14 = Canvas(cutBitmap14)
        var desRect14 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect14 = Rect(bitmap.width / 4, 3 * bitmap.height / 5, bitmap.width / 2, 4 * bitmap.height / 5)
        canvas14.drawBitmap(bitmap, srcRect14, desRect14, null)
        myImageViewSplit170.setImageBitmap(cutBitmap14)

        var cutBitmap15 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas15 = Canvas(cutBitmap15)
        var desRect15 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect15 = Rect(bitmap.width / 2, 3 * bitmap.height / 5, 3 * bitmap.width / 4, 4 * bitmap.height / 5)
        canvas15.drawBitmap(bitmap, srcRect15, desRect15, null)
        myImageViewSplit171.setImageBitmap(cutBitmap15)

        var cutBitmap16 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas16 = Canvas(cutBitmap16)
        var desRect16 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect16 = Rect(3 * bitmap.width / 4, 3 * bitmap.height / 5, bitmap.width, 4 * bitmap.height / 5)
        canvas16.drawBitmap(bitmap, srcRect16, desRect16, null)
        myImageViewSplit172.setImageBitmap(cutBitmap16)

        var cutBitmap17 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas17 = Canvas(cutBitmap17)
        var desRect17 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect17 = Rect(0, 4 * bitmap.height / 5, bitmap.width / 4, bitmap.height)
        canvas17.drawBitmap(bitmap, srcRect17, desRect17, null)
        myImageViewSplit173.setImageBitmap(cutBitmap17)

        var cutBitmap18 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas18 = Canvas(cutBitmap18)
        var desRect18 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect18 = Rect(bitmap.width / 4, 4 * bitmap.height / 5, bitmap.width / 2, bitmap.height)
        canvas18.drawBitmap(bitmap, srcRect18, desRect18, null)
        myImageViewSplit174.setImageBitmap(cutBitmap18)

        var cutBitmap19 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas19 = Canvas(cutBitmap19)
        var desRect19 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect19 = Rect(bitmap.width / 2, 4 * bitmap.height / 5, 3 * bitmap.width / 4, bitmap.height)
        canvas19.drawBitmap(bitmap, srcRect19, desRect19, null)
        myImageViewSplit175.setImageBitmap(cutBitmap19)

        var cutBitmap20 = Bitmap.createBitmap(bitmap.width / 4, bitmap.height / 5, Bitmap.Config.ARGB_8888)
        var canvas20 = Canvas(cutBitmap20)
        var desRect20 = Rect(0, 0, bitmap.width / 4, bitmap.height / 5)
        var srcRect20 = Rect(3 * bitmap.width / 4, 4 * bitmap.height / 5, bitmap.width, bitmap.height)
        canvas20.drawBitmap(bitmap, srcRect20, desRect20, null)
        myImageViewSplit176.setImageBitmap(cutBitmap20)
    }

    private fun splitImage5x4() {
        val bitmap = this.intent.getParcelableExtra<Bitmap>("Bitmap")

        var cutBitmap1 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas1 = Canvas(cutBitmap1)
        var desRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect1 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        canvas1.drawBitmap(bitmap, srcRect1, desRect1, null)
        myImageViewSplit177.setImageBitmap(cutBitmap1)

        var cutBitmap2 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas2 = Canvas(cutBitmap2)
        var desRect2 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect2 = Rect(bitmap.width / 5, 0, 2 * bitmap.width / 5, bitmap.height / 4)
        canvas2.drawBitmap(bitmap, srcRect2, desRect2, null)
        myImageViewSplit178.setImageBitmap(cutBitmap2)

        var cutBitmap3 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas3 = Canvas(cutBitmap3)
        var desRect3 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect3 = Rect(2 * bitmap.width / 5, 0, 3 * bitmap.width / 5, bitmap.height / 4)
        canvas3.drawBitmap(bitmap, srcRect3, desRect3, null)
        myImageViewSplit179.setImageBitmap(cutBitmap3)

        var cutBitmap4 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas4 = Canvas(cutBitmap4)
        var desRect4 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect4 = Rect(3 * bitmap.width / 5, 0, 4 * bitmap.width / 5, bitmap.height / 4)
        canvas4.drawBitmap(bitmap, srcRect4, desRect4, null)
        myImageViewSplit180.setImageBitmap(cutBitmap4)

        var cutBitmap5 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas5 = Canvas(cutBitmap5)
        var desRect5 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect5 = Rect(4 * bitmap.width / 5, 0, bitmap.width, bitmap.height / 4)
        canvas5.drawBitmap(bitmap, srcRect5, desRect5, null)
        myImageViewSplit181.setImageBitmap(cutBitmap5)

        var cutBitmap6 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas6 = Canvas(cutBitmap6)
        var desRect6 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect6 = Rect(0, bitmap.height / 4, bitmap.width / 5, bitmap.height / 2)
        canvas6.drawBitmap(bitmap, srcRect6, desRect6, null)
        myImageViewSplit182.setImageBitmap(cutBitmap6)

        var cutBitmap7 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas7 = Canvas(cutBitmap7)
        var desRect7 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect7 = Rect(bitmap.width / 5, bitmap.height / 4, 2 * bitmap.width / 5, bitmap.height / 2)
        canvas7.drawBitmap(bitmap, srcRect7, desRect7, null)
        myImageViewSplit183.setImageBitmap(cutBitmap7)

        var cutBitmap8 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas8 = Canvas(cutBitmap8)
        var desRect8 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect8 = Rect(2 * bitmap.width / 5, bitmap.height / 4, 3 * bitmap.width / 5, bitmap.height / 2)
        canvas8.drawBitmap(bitmap, srcRect8, desRect8, null)
        myImageViewSplit184.setImageBitmap(cutBitmap8)

        var cutBitmap9 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas9 = Canvas(cutBitmap9)
        var desRect9 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect9 = Rect(3 * bitmap.width / 5, bitmap.height / 4, 4 * bitmap.width / 5, bitmap.height / 2)
        canvas9.drawBitmap(bitmap, srcRect9, desRect9, null)
        myImageViewSplit185.setImageBitmap(cutBitmap9)

        var cutBitmap10 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas10 = Canvas(cutBitmap10)
        var desRect10 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect10 = Rect(4 * bitmap.width / 5, bitmap.height / 4, bitmap.width, bitmap.height / 2)
        canvas10.drawBitmap(bitmap, srcRect10, desRect10, null)
        myImageViewSplit186.setImageBitmap(cutBitmap10)

        var cutBitmap11 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas11 = Canvas(cutBitmap11)
        var desRect11 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect11 = Rect(0, bitmap.height / 2, bitmap.width / 5, 3 * bitmap.height / 4)
        canvas11.drawBitmap(bitmap, srcRect11, desRect11, null)
        myImageViewSplit187.setImageBitmap(cutBitmap11)

        var cutBitmap12 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas12 = Canvas(cutBitmap12)
        var desRect12 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect12 = Rect(bitmap.width / 5, bitmap.height / 2, 2 * bitmap.width / 5, 3 * bitmap.height / 4)
        canvas12.drawBitmap(bitmap, srcRect12, desRect12, null)
        myImageViewSplit188.setImageBitmap(cutBitmap12)

        var cutBitmap13 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas13 = Canvas(cutBitmap13)
        var desRect13 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect13 = Rect(2 * bitmap.width / 5, bitmap.height / 2, 3 * bitmap.width / 5, 3 * bitmap.height / 4)
        canvas13.drawBitmap(bitmap, srcRect13, desRect13, null)
        myImageViewSplit189.setImageBitmap(cutBitmap13)

        var cutBitmap14 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas14 = Canvas(cutBitmap14)
        var desRect14 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect14 = Rect(3 * bitmap.width / 5, bitmap.height / 2, 4 * bitmap.width / 5, 3 * bitmap.height / 4)
        canvas14.drawBitmap(bitmap, srcRect14, desRect14, null)
        myImageViewSplit190.setImageBitmap(cutBitmap14)

        var cutBitmap15 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas15 = Canvas(cutBitmap15)
        var desRect15 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect15 = Rect(4 * bitmap.width / 5, bitmap.height / 2, bitmap.width, 3 * bitmap.height / 4)
        canvas15.drawBitmap(bitmap, srcRect15, desRect15, null)
        myImageViewSplit191.setImageBitmap(cutBitmap15)

        var cutBitmap16 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas16 = Canvas(cutBitmap16)
        var desRect16 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect16 = Rect(0, 3 * bitmap.height / 4, bitmap.width / 5, bitmap.height)
        canvas16.drawBitmap(bitmap, srcRect16, desRect16, null)
        myImageViewSplit192.setImageBitmap(cutBitmap16)

        var cutBitmap17 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas17 = Canvas(cutBitmap17)
        var desRect17 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect17 = Rect(bitmap.width / 5, 3 * bitmap.height / 4, 2 * bitmap.width / 5, bitmap.height)
        canvas17.drawBitmap(bitmap, srcRect17, desRect17, null)
        myImageViewSplit193.setImageBitmap(cutBitmap17)

        var cutBitmap18 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas18 = Canvas(cutBitmap18)
        var desRect18 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect18 = Rect(2 * bitmap.width / 5, 3 * bitmap.height / 4, 3 * bitmap.width / 5, bitmap.height)
        canvas18.drawBitmap(bitmap, srcRect18, desRect18, null)
        myImageViewSplit194.setImageBitmap(cutBitmap18)

        var cutBitmap19 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas19 = Canvas(cutBitmap19)
        var desRect19 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect19 = Rect(3 * bitmap.width / 5, 3 * bitmap.height / 4, 4 * bitmap.width / 5, bitmap.height)
        canvas19.drawBitmap(bitmap, srcRect19, desRect19, null)
        myImageViewSplit195.setImageBitmap(cutBitmap19)

        var cutBitmap20 = Bitmap.createBitmap(bitmap.width / 5, bitmap.height / 4, Bitmap.Config.ARGB_8888)
        var canvas20 = Canvas(cutBitmap20)
        var desRect20 = Rect(0, 0, bitmap.width / 5, bitmap.height / 4)
        var srcRect20 = Rect(4 * bitmap.width / 5, 3 * bitmap.height / 4, bitmap.width, bitmap.height)
        canvas20.drawBitmap(bitmap, srcRect20, desRect20, null)
        myImageViewSplit196.setImageBitmap(cutBitmap20)
    }
}
